server:
  port: 1026
management:
  port: 1031
spring:
  application:
    name: turbine
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds:  10
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:password@eureka-dev:8761/eureka
logging:
  file: ${spring.application.name}.log
turbine:
  app-config: eureka-consumer-ribbon-hystrix
  cluster-name-expression: 'default'
  combine-host-port: true


