server:
  port: 1035
spring:
  application:
    name: swagger-service-b
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds:  10
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:password@eureka-dev:8761/eureka
swagger:
  base-package: com.chengshi.swaggerserviceb

