spring:
  application:
    name: turbine-amqp
server:
  port: 1027
management:
  port: 1032
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds:  10
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:password@eureka-dev:8761/eureka
logging:
  file: ${spring.application.name}.log